### ISSUE TITLE
feat: replace reactive store with Pinia

### ISSUE THREAD

**Issue by gioboa** [gioboa/vue-microfrontend-demo#1]

**Comment by gioboa** [comment]
👋 @oceangravity you can create a PR for this feature. Thanks 😉

**Comment by oceangravity** [comment]
Hi ☺ @gioboa many thanks, yeah sure, my pleasure. Can I be mantainer?

**Comment by gioboa** [comment]
You can open a PR by forking the project because my plan, after this feature, is to move this project under https://github.com/module-federation/module-federation-examples 
what functionality would you like in this example?

**Comment by oceangravity** [comment]
Sorry, I forget how GitHub works 😁, but PR is ready.

I found some other issues related:

- Can’t resolve path references like `@/`
- Issues with SVG images because there's no loader in the esbuild plugin for Vue (I guess).
- Issues with style tag in remote modules.

I'm guessing that those issues are related to "esbuild-plugin-vue-next"

Expected functionality:

Dev mode in host and remotes. Without HMR it's a really pain.

Thank you @gioboa
